import os

from utils.core_utils import generate_csv_report, get_boto_client, upload_file_to_s3
from utils.extract_data_utils import extract_mysql_data, extract_postgres_data
from utils.transform_data_utils import transform_data


def main():
    """
    Generates a report with the number of daily lessons completed by users
    in the last year and saves it to a CSV file.

    The report is generated by extracting user and lessons data from
    PostgreSQL and MySQL databases, respectively. The data is then
    transformed into the required format and saved to a CSV file.
    """

    # extract data
    users_data = extract_postgres_data()
    lessons_data = extract_mysql_data()

    # transform data
    report_data = transform_data(users_data=users_data, lessons_data=lessons_data)

    # export data
    file_name = f"{os.getenv('REPORT_FILE_NAME')}.csv"
    generate_csv_report(report_df=report_data, file_name=file_name)
    upload_file_to_s3(s3_client=get_boto_client("s3"), file_name=file_name)


if __name__ == "__main__":
    main()
